### ISSUE TITLE
React Native Web Support

### ISSUE THREAD

**Issue by RobertSasak** [cbbfcd/react-native-lightbox#7]
This issue is intended for anybody else who is looking for Web support. Current version do not support it. For some strange reason in version 0.8.8 there are missing "const" when declaring _getContent_. Adding those make the library works on web.

However this is already fixed in latest version 0.8.9-beta.0.

```sh
yarn add react-native-lightbox-v2@0.8.9-beta.0
```
This issue can be closed once a new stable version is released.

**Comment by cbbfcd** [comment]
yes, we will change to a stable version very soon~

**Comment by cbbfcd** [comment]
v0.9.0 🚀
