### ISSUE TITLE
image not full size in viewing mode

### ISSUE THREAD

**Issue by fukemy** [cbbfcd/react-native-lightbox#8]
hi, please help my problem:
![Screen Shot 2022-04-21 at 15 15 23](https://user-images.githubusercontent.com/8202437/164410968-873431b4-3c20-4da9-8f57-05af239b5a7e.png)
![Screen Shot 2022-04-21 at 15 15 31](https://user-images.githubusercontent.com/8202437/164410991-6fc96b51-5469-49b8-bf01-5af162baa116.png)

here is my code:

```

//chatscreen
 const renderImageView = (props) => {
        if(props.currentMessage.image){
            return <ChatImage {...props}/>
        }
        return null
    }

export function ChatImage(props) {
    console.log(props.currentMessage.image)
    return (
        <LightBox navigator={null}>
            <Image
                style={{
                    width: 180,
                    height: 180,
                    borderRadius: 8
                }}
                resizeMode='cover'
                source={{ uri: props.currentMessage.image }}
            />
        </LightBox>
    )
}
```

**Comment by cbbfcd** [comment]
sorry for late response, i think there are some workround, biz i can't reproduce this problem.
1. `renderContent ` can custom your overlay display.
2.  LightBox add a style {{ flex: 1 }}.

i hope it can help you

**Comment by fukemy** [comment]
hi, it's worked. THanks

**Comment by sadia-onyxtec** [comment]
> sorry for late response, i think there are some workround, biz i can't reproduce this problem.
> 
>     1. `renderContent ` can custom your overlay display.
> 
>     2. LightBox add a style {{ flex: 1 }}.
> 
> 
> i hope it can help you

It was not working but when I added flex:1 in activeProps, it worked fine.
